const googleVNFonts = [
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'Open Sans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Source Sans Pro', value: 'Source Sans Pro' },
  { label: 'Roboto Condensed', value: 'Roboto Condensed' },
  { label: 'Oswald', value: 'Oswald' },
  { label: 'Roboto Mono', value: 'Roboto Mono' },
  { label: 'Raleway', value: 'Raleway' },
  { label: 'Noto Sans', value: 'Noto Sans' },
  { label: 'Recursive', value: 'Recursive' },
  { label: 'Roboto Slab', value: 'Roboto Slab' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Playfair Display', value: 'Playfair Display' },
  { label: 'Nunito', value: 'Nunito' },
  { label: 'Open Sans Condensed', value: 'Open Sans Condensed' },
  { label: 'Lora', value: 'Lora' },
  { label: 'Noto Serif', value: 'Noto Serif' },
  { label: 'Work Sans', value: 'Work Sans' },
  { label: 'Nunito Sans', value: 'Nunito Sans' },
  { label: 'Fira Sans', value: 'Fira Sans' },
  { label: 'Quicksand', value: 'Quicksand' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Barlow', value: 'Barlow' },
  { label: 'Inconsolata', value: 'Inconsolata' },
  { label: 'Source Code Pro', value: 'Source Code Pro' },
  { label: 'Dosis', value: 'Dosis' },
  { label: 'Josefin Sans', value: 'Josefin Sans' },
  { label: 'Arimo', value: 'Arimo' },
  { label: 'Libre Franklin', value: 'Libre Franklin' },
  { label: 'Anton', value: 'Anton' },
  { label: 'Cabin', value: 'Cabin' },
  { label: 'Bitter', value: 'Bitter' },
  { label: 'IBM Plex Sans', value: 'IBM Plex Sans' },
  { label: 'Lobster', value: 'Lobster' },
  { label: 'Dancing Script', value: 'Dancing Script' },
  { label: 'Source Serif Pro', value: 'Source Serif Pro' },
  { label: 'Yanone Kaffeesatz', value: 'Yanone Kaffeesatz' },
  { label: 'Oi', value: 'Oi' },
  { label: 'Varela Round', value: 'Varela Round' },
  { label: 'Comfortaa', value: 'Comfortaa' },
  { label: 'Barlow Condensed', value: 'Barlow Condensed' },
  { label: 'Exo 2', value: 'Exo 2' },
  { label: 'EB Garamond', value: 'EB Garamond' },
  { label: 'Merriweather Sans', value: 'Merriweather Sans' },
  { label: 'Pacifico', value: 'Pacifico' },
  { label: 'Cormorant Unicase', value: 'Cormorant Unicase' },
  { label: 'Archivo Narrow', value: 'Archivo Narrow' },
  { label: 'Prompt', value: 'Prompt' },
  { label: 'Kanit', value: 'Kanit' },
  { label: 'Asap', value: 'Asap' },
  { label: 'Questrial', value: 'Questrial' },
  { label: 'Exo', value: 'Exo' },
  { label: 'Cormorant Garamond', value: 'Cormorant Garamond' },
  { label: 'Maven Pro', value: 'Maven Pro' },
  { label: 'Brygada 1918', value: 'Brygada 1918' },
  { label: 'Amatic SC', value: 'Amatic SC' },
  { label: 'Play', value: 'Play' },
  { label: 'Fira Sans Condensed', value: 'Fira Sans Condensed' },
  { label: 'IBM Plex Serif', value: 'IBM Plex Serif' },
  { label: 'Signika', value: 'Signika' },
  { label: 'Patrick Hand', value: 'Patrick Hand' },
  { label: 'Barlow Semi Condensed', value: 'Barlow Semi Condensed' },
  { label: 'Alfa Slab One', value: 'Alfa Slab One' },
  { label: 'Vollkorn', value: 'Vollkorn' },
  { label: 'Mulish', value: 'Mulish' },
  { label: 'Archivo', value: 'Archivo' },
  { label: 'Alegreya Sans', value: 'Alegreya Sans' },
  { label: 'Alegreya', value: 'Alegreya' },
  { label: 'M PLUS Rounded 1c', value: 'M PLUS Rounded 1c' },
  { label: 'Encode Sans', value: 'Encode Sans' },
  { label: 'Prata', value: 'Prata' },
  { label: 'Tinos', value: 'Tinos' },
  { label: 'M PLUS 1p', value: 'M PLUS 1p' },
  { label: 'Francois One', value: 'Francois One' },
  { label: 'IBM Plex Mono', value: 'IBM Plex Mono' },
  { label: 'Cuprum', value: 'Cuprum' },
  { label: 'Baloo 2', value: 'Baloo 2' },
  { label: 'Noticia Text', value: 'Noticia Text' },
  { label: 'Rokkitt', value: 'Rokkitt' },
  { label: 'Old Standard TT', value: 'Old Standard TT' },
  { label: 'Sarabun', value: 'Sarabun' },
  { label: 'Asap Condensed', value: 'Asap Condensed' },
  { label: 'Saira Condensed', value: 'Saira Condensed' },
  { label: 'Playfair Display SC', value: 'Playfair Display SC' },
  { label: 'Paytone One', value: 'Paytone One' },
  { label: 'Montserrat Alternates', value: 'Montserrat Alternates' },
  {
    label: 'Fira Sans Extra Condensed',
    value: 'Fira Sans Extra Condensed',
  },
  { label: 'Spectral', value: 'Spectral' },
  { label: 'JetBrains Mono', value: 'JetBrains Mono' },
  { label: 'Philosopher', value: 'Philosopher' },
  { label: 'Jura', value: 'Jura' },
  { label: 'Cormorant', value: 'Cormorant' },
  { label: 'Ruda', value: 'Ruda' },
  { label: 'Bangers', value: 'Bangers' },
  { label: 'Saira', value: 'Saira' },
  { label: 'Chakra Petch', value: 'Chakra Petch' },
  { label: 'Taviraj', value: 'Taviraj' },
  { label: 'Srisakdi', value: 'Srisakdi' },
  { label: 'Faustina', value: 'Faustina' },
  { label: 'Mitr', value: 'Mitr' },
  { label: 'Truculenta', value: 'Truculenta' },
  { label: 'Sigmar One', value: 'Sigmar One' },
  { label: 'Cabin Condensed', value: 'Cabin Condensed' },
  { label: 'Encode Sans Condensed', value: 'Encode Sans Condensed' },
  { label: 'Space Mono', value: 'Space Mono' },
  { label: 'Bungee', value: 'Bungee' },
  { label: 'Bai Jamjuree', value: 'Bai Jamjuree' },
  { label: 'Sawarabi Gothic', value: 'Sawarabi Gothic' },
  { label: 'Potta One', value: 'Potta One' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Pangolin', value: 'Pangolin' },
  { label: 'Markazi Text', value: 'Markazi Text' },
  { label: 'Alata', value: 'Alata' },
  { label: 'Imbue', value: 'Imbue' },
  { label: 'Yeseva One', value: 'Yeseva One' },
  { label: 'Gelasio', value: 'Gelasio' },
  { label: 'Krub', value: 'Krub' },
  { label: 'Baloo Tamma 2', value: 'Baloo Tamma 2' },
  { label: 'Saira Semi Condensed', value: 'Saira Semi Condensed' },
  { label: 'Pridi', value: 'Pridi' },
  { label: 'Sriracha', value: 'Sriracha' },
  { label: 'Crimson Pro', value: 'Crimson Pro' },
  { label: 'Arima Madurai', value: 'Arima Madurai' },
  { label: 'Arsenal', value: 'Arsenal' },
  { label: 'Baloo Chettan 2', value: 'Baloo Chettan 2' },
  { label: 'Itim', value: 'Itim' },
  { label: 'Cousine', value: 'Cousine' },
  { label: 'Baloo Tammudu 2', value: 'Baloo Tammudu 2' },
  { label: 'Andika New Basic', value: 'Andika New Basic' },
  { label: 'Saira Extra Condensed', value: 'Saira Extra Condensed' },
  { label: 'Alegreya Sans SC', value: 'Alegreya Sans SC' },
  { label: 'Texturina', value: 'Texturina' },
  { label: 'Lexend Deca', value: 'Lexend Deca' },
  { label: 'Bevan', value: 'Bevan' },
  { label: 'VT323', value: 'VT323' },
  { label: 'Lalezar', value: 'Lalezar' },
  { label: 'Lemonada', value: 'Lemonada' },
  { label: 'Charm', value: 'Charm' },
  { label: 'Trirong', value: 'Trirong' },
  { label: 'Baloo Da 2', value: 'Baloo Da 2' },
  { label: 'Chonburi', value: 'Chonburi' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Pattaya', value: 'Pattaya' },
  { label: 'Alegreya SC', value: 'Alegreya SC' },
  { label: 'Thasadith', value: 'Thasadith' },
  { label: 'Bungee Inline', value: 'Bungee Inline' },
  {
    label: 'Big Shoulders Stencil Text',
    value: 'Big Shoulders Stencil Text',
  },
  {
    label: 'Big Shoulders Inline Display',
    value: 'Big Shoulders Inline Display',
  },
  {
    label: 'Big Shoulders Stencil Display',
    value: 'Big Shoulders Stencil Display',
  },
  {
    label: 'Big Shoulders Inline Text',
    value: 'Big Shoulders Inline Text',
  },
  { label: 'Judson', value: 'Judson' },
  { label: 'Alatsi', value: 'Alatsi' },
  { label: 'IBM Plex Sans Condensed', value: 'IBM Plex Sans Condensed' },
  { label: 'Niramit', value: 'Niramit' },
  { label: 'Piazzolla', value: 'Piazzolla' },
  { label: 'Space Grotesk', value: 'Space Grotesk' },
  { label: 'Maitree', value: 'Maitree' },
  { label: 'Rosario', value: 'Rosario' },
  { label: 'Darker Grotesque', value: 'Darker Grotesque' },
  { label: 'Metrophobic', value: 'Metrophobic' },
  { label: 'Athiti', value: 'Athiti' },
  { label: 'Trispace', value: 'Trispace' },
  { label: 'Epilogue', value: 'Epilogue' },
  { label: 'Big Shoulders Display', value: 'Big Shoulders Display' },
  { label: 'Cormorant Infant', value: 'Cormorant Infant' },
  { label: 'Podkova', value: 'Podkova' },
  { label: 'K2D', value: 'K2D' },
  { label: 'Ballet', value: 'Ballet' },
  { label: 'Spectral SC', value: 'Spectral SC' },
  { label: 'Cormorant SC', value: 'Cormorant SC' },
  { label: 'Sansita Swashed', value: 'Sansita Swashed' },
  { label: 'Grandstander', value: 'Grandstander' },
  {
    label: 'Encode Sans Semi Condensed',
    value: 'Encode Sans Semi Condensed',
  },
  { label: 'Be Vietnam', value: 'Be Vietnam' },
  { label: 'Sedgwick Ave', value: 'Sedgwick Ave' },
  { label: 'Bungee Shade', value: 'Bungee Shade' },
  { label: 'Hepta Slab', value: 'Hepta Slab' },
  { label: 'Andika', value: 'Andika' },
  { label: 'Fraunces', value: 'Fraunces' },
  { label: 'Patrick Hand SC', value: 'Patrick Hand SC' },
  { label: 'Grenze Gotisch', value: 'Grenze Gotisch' },
  { label: 'Petrona', value: 'Petrona' },
  { label: 'Commissioner', value: 'Commissioner' },
  { label: 'David Libre', value: 'David Libre' },
  { label: 'Baloo Thambi 2', value: 'Baloo Thambi 2' },
  { label: 'Kufam', value: 'Kufam' },
  { label: 'Xanh Mono', value: 'Xanh Mono' },
  { label: 'Encode Sans Expanded', value: 'Encode Sans Expanded' },
  { label: 'Newsreader', value: 'Newsreader' },
  { label: 'Red Rose', value: 'Red Rose' },
  { label: 'Vollkorn SC', value: 'Vollkorn SC' },
  { label: 'Goldman', value: 'Goldman' },
  { label: 'Calistoga', value: 'Calistoga' },
  { label: 'Cormorant Upright', value: 'Cormorant Upright' },
  { label: 'Big Shoulders Text', value: 'Big Shoulders Text' },
  { label: 'Manuale', value: 'Manuale' },
  { label: 'Livvic', value: 'Livvic' },
  { label: 'Coiny', value: 'Coiny' },
  { label: 'Major Mono Display', value: 'Major Mono Display' },
  { label: 'Varta', value: 'Varta' },
  { label: 'MuseoModerno', value: 'MuseoModerno' },
  { label: 'Lexend Zetta', value: 'Lexend Zetta' },
  {
    label: 'Encode Sans Semi Expanded',
    value: 'Encode Sans Semi Expanded',
  },
  { label: 'Bellota Text', value: 'Bellota Text' },
  { label: 'Kodchasan', value: 'Kodchasan' },
  { label: 'Baloo Bhaina 2', value: 'Baloo Bhaina 2' },
  { label: 'Baloo Bhai 2', value: 'Baloo Bhai 2' },
  { label: 'Baloo Paaji 2', value: 'Baloo Paaji 2' },
  { label: 'Farsan', value: 'Farsan' },
  { label: 'KoHo', value: 'KoHo' },
  { label: 'Bellota', value: 'Bellota' },
  { label: 'Fahkwang', value: 'Fahkwang' },
  { label: 'Saira Stencil One', value: 'Saira Stencil One' },
  { label: 'Rowdies', value: 'Rowdies' },
  { label: 'Lexend Exa', value: 'Lexend Exa' },
  { label: 'Gotu', value: 'Gotu' },
  { label: 'Charmonman', value: 'Charmonman' },
  { label: 'Bungee Outline', value: 'Bungee Outline' },
  { label: 'Lexend Mega', value: 'Lexend Mega' },
  { label: 'Viaoda Libre', value: 'Viaoda Libre' },
  { label: 'Lexend Giga', value: 'Lexend Giga' },
  { label: 'Sedgwick Ave Display', value: 'Sedgwick Ave Display' },
  { label: 'Barriecito', value: 'Barriecito' },
  { label: 'Lexend Tera', value: 'Lexend Tera' },
  { label: 'Lexend Peta', value: 'Lexend Peta' },
  { label: 'Bungee Hairline', value: 'Bungee Hairline' },
  { label: 'Bahianita', value: 'Bahianita' },
  { label: 'Grenze', value: 'Grenze' },
];

const googleFonts = [
  ...googleVNFonts,
  { label: 'Russo One', value: 'Russo One' },
  { label: 'Do Hyeon', value: 'Do Hyeon' },
  { label: 'Poppins', value: 'Poppins' },
  { label: 'Noto Sans JP', value: 'Noto Sans JP' },
  { label: 'Lato', value: 'Lato' },
  { label: 'PT Sans', value: 'PT Sans' },
  { label: 'Ubuntu', value: 'Ubuntu' },
  { label: 'Libre Caslon Display', value: 'Libre Caslon Display' },
  { label: 'PT Serif', value: 'PT Serif' },
  { label: 'Rubik', value: 'Rubik' },
  { label: 'Noto Sans KR', value: 'Noto Sans KR' },
  { label: 'Nanum Gothic', value: 'Nanum Gothic' },
  { label: 'Titillium Web', value: 'Titillium Web' },
  { label: 'Mukta', value: 'Mukta' },
  { label: 'Noto Sans TC', value: 'Noto Sans TC' },
  { label: 'Heebo', value: 'Heebo' },
  { label: 'PT Sans Narrow', value: 'PT Sans Narrow' },
  { label: 'Oxygen', value: 'Oxygen' },
  { label: 'Bebas Neue', value: 'Bebas Neue' },
  { label: 'Slabo 27px', value: 'Slabo 27px' },
  { label: 'Karla', value: 'Karla' },
  { label: 'Hind Siliguri', value: 'Hind Siliguri' },
  { label: 'Crimson Text', value: 'Crimson Text' },
  { label: 'Libre Baskerville', value: 'Libre Baskerville' },
  { label: 'Londrina Solid', value: 'Londrina Solid' },
  { label: 'Hind', value: 'Hind' },
  { label: 'Fjalla One', value: 'Fjalla One' },
  { label: 'Abel', value: 'Abel' },
  { label: 'Overpass', value: 'Overpass' },
  { label: 'Cairo', value: 'Cairo' },
  { label: 'Arvo', value: 'Arvo' },
  { label: 'Balsamiq Sans', value: 'Balsamiq Sans' },
  { label: 'Indie Flower', value: 'Indie Flower' },
  { label: 'Zilla Slab', value: 'Zilla Slab' },
  { label: 'Teko', value: 'Teko' },
  { label: 'Noto Sans SC', value: 'Noto Sans SC' },
  { label: 'Shadows Into Light', value: 'Shadows Into Light' },
  { label: 'Abril Fatface', value: 'Abril Fatface' },
  { label: 'Catamaran', value: 'Catamaran' },
  { label: 'Bree Serif', value: 'Bree Serif' },
  { label: 'Monda', value: 'Monda' },
  { label: 'Acme', value: 'Acme' },
  { label: 'Antic Slab', value: 'Antic Slab' },
  { label: 'Architects Daughter', value: 'Architects Daughter' },
  { label: 'Raleway Dots', value: 'Raleway Dots' },
  { label: 'Martel', value: 'Martel' },
  { label: 'Assistant', value: 'Assistant' },
  { label: 'Domine', value: 'Domine' },
  { label: 'Permanent Marker', value: 'Permanent Marker' },
  { label: 'Righteous', value: 'Righteous' },
  { label: 'Hind Madurai', value: 'Hind Madurai' },
  { label: 'Tajawal', value: 'Tajawal' },
  { label: 'Noto Sans HK', value: 'Noto Sans HK' },
  { label: 'Patua One', value: 'Patua One' },
  { label: 'Fredoka One', value: 'Fredoka One' },
  { label: 'Amiri', value: 'Amiri' },
  { label: 'Manrope', value: 'Manrope' },
  { label: 'PT Sans Caption', value: 'PT Sans Caption' },
  { label: 'Caveat', value: 'Caveat' },
  { label: 'DM Sans', value: 'DM Sans' },
  { label: 'Crete Round', value: 'Crete Round' },
  { label: 'Rajdhani', value: 'Rajdhani' },
  { label: 'Nanum Myeongjo', value: 'Nanum Myeongjo' },
  { label: 'Ubuntu Condensed', value: 'Ubuntu Condensed' },
  { label: 'Satisfy', value: 'Satisfy' },
  { label: 'Noto Serif JP', value: 'Noto Serif JP' },
  { label: 'Alike Angular', value: 'Alike Angular' },
  { label: 'Cantarell', value: 'Cantarell' },
  { label: 'ABeeZee', value: 'ABeeZee' },
  { label: 'Cinzel', value: 'Cinzel' },
  { label: 'Courgette', value: 'Courgette' },
  { label: 'Archivo Black', value: 'Archivo Black' },
  { label: 'Lobster Two', value: 'Lobster Two' },
  { label: 'Kaushan Script', value: 'Kaushan Script' },
  { label: 'Frank Ruhl Libre', value: 'Frank Ruhl Libre' },
  { label: 'Cardo', value: 'Cardo' },
  { label: 'Kalam', value: 'Kalam' },
  { label: 'Concert One', value: 'Concert One' },
  { label: 'Pathway Gothic One', value: 'Pathway Gothic One' },
  { label: 'Great Vibes', value: 'Great Vibes' },
  { label: 'Hind Vadodara', value: 'Hind Vadodara' },
  { label: 'Sacramento', value: 'Sacramento' },
  { label: 'Volkhov', value: 'Volkhov' },
  { label: 'Luckiest Guy', value: 'Luckiest Guy' },
  { label: 'Changa', value: 'Changa' },
  { label: 'News Cycle', value: 'News Cycle' },
  { label: 'Advent Pro', value: 'Advent Pro' },
  { label: 'Ropa Sans', value: 'Ropa Sans' },
  { label: 'Yantramanav', value: 'Yantramanav' },
  { label: 'Passion One', value: 'Passion One' },
  { label: 'Special Elite', value: 'Special Elite' },
  { label: 'Pragati Narrow', value: 'Pragati Narrow' },
  { label: 'Quattrocento Sans', value: 'Quattrocento Sans' },
  { label: 'Orbitron', value: 'Orbitron' },
  { label: 'Gloria Hallelujah', value: 'Gloria Hallelujah' },
  { label: 'Didact Gothic', value: 'Didact Gothic' },
  { label: 'Electrolize', value: 'Electrolize' },
  { label: 'Schoolbell', value: 'Schoolbell' },
  { label: 'Krona One', value: 'Krona One' },
  { label: 'Chivo', value: 'Chivo' },
  { label: 'Neuton', value: 'Neuton' },
  { label: 'Sawarabi Mincho', value: 'Sawarabi Mincho' },
  { label: 'Poiret One', value: 'Poiret One' },
  { label: 'Josefin Slab', value: 'Josefin Slab' },
  { label: 'Ramabhadra', value: 'Ramabhadra' },
  { label: 'Yellowtail', value: 'Yellowtail' },
  { label: 'Istok Web', value: 'Istok Web' },
  { label: 'Ultra', value: 'Ultra' },
  { label: 'Almarai', value: 'Almarai' },
  { label: 'Hind Guntur', value: 'Hind Guntur' },
  { label: 'Parisienne', value: 'Parisienne' },
  { label: 'Quattrocento', value: 'Quattrocento' },
  { label: 'BenchNine', value: 'BenchNine' },
  { label: 'Cookie', value: 'Cookie' },
  { label: 'Unica One', value: 'Unica One' },
  { label: 'Khand', value: 'Khand' },
  { label: 'Staatliches', value: 'Staatliches' },
  { label: 'Gudea', value: 'Gudea' },
  { label: 'Playball', value: 'Playball' },
  { label: 'Sora', value: 'Sora' },
  { label: 'Vidaloka', value: 'Vidaloka' },
  { label: 'Squada One', value: 'Squada One' },
  { label: 'Shanti', value: 'Shanti' },
  { label: 'Press Start 2P', value: 'Press Start 2P' },
  { label: 'Monoton', value: 'Monoton' },
  { label: 'Sanchez', value: 'Sanchez' },
  { label: 'Arapey', value: 'Arapey' },
  { label: 'Jaldi', value: 'Jaldi' },
  { label: 'Karma', value: 'Karma' },
  { label: 'Neucha', value: 'Neucha' },
  { label: 'Alice', value: 'Alice' },
  { label: 'Hammersmith One', value: 'Hammersmith One' },
  { label: 'Gentium Basic', value: 'Gentium Basic' },
  { label: 'Economica', value: 'Economica' },
  { label: 'Gothic A1', value: 'Gothic A1' },
  { label: 'Spartan', value: 'Spartan' },
  { label: 'El Messiri', value: 'El Messiri' },
  { label: 'Oleo Script', value: 'Oleo Script' },
  { label: 'Handlee', value: 'Handlee' },
  { label: 'Adamina', value: 'Adamina' },
  { label: 'Viga', value: 'Viga' },
  { label: 'Tangerine', value: 'Tangerine' },
  { label: 'Fugaz One', value: 'Fugaz One' },
  { label: 'Rock Salt', value: 'Rock Salt' },
  { label: 'Amaranth', value: 'Amaranth' },
  { label: 'Aclonica', value: 'Aclonica' },
  { label: 'Katibeh', value: 'Katibeh' },
  { label: 'Marck Script', value: 'Marck Script' },
  { label: 'Gochi Hand', value: 'Gochi Hand' },
  { label: 'Armata', value: 'Armata' },
  { label: 'Pontano Sans', value: 'Pontano Sans' },
  { label: 'Bad Script', value: 'Bad Script' },
  { label: 'Merienda', value: 'Merienda' },
  { label: 'Actor', value: 'Actor' },
  { label: 'Alef', value: 'Alef' },
  { label: 'Julius Sans One', value: 'Julius Sans One' },
  { label: 'PT Mono', value: 'PT Mono' },
  { label: 'Nanum Gothic Coding', value: 'Nanum Gothic Coding' },
  { label: 'Lusitana', value: 'Lusitana' },
  { label: 'Allura', value: 'Allura' },
  { label: 'Quantico', value: 'Quantico' },
  { label: 'Palanquin', value: 'Palanquin' },
  { label: 'Audiowide', value: 'Audiowide' },
  { label: 'Gentium Book Basic', value: 'Gentium Book Basic' },
  { label: 'Abhaya Libre', value: 'Abhaya Libre' },
  { label: 'Noto Serif TC', value: 'Noto Serif TC' },
  { label: 'Sorts Mill Goudy', value: 'Sorts Mill Goudy' },
  { label: 'Pinyon Script', value: 'Pinyon Script' },
  { label: 'Carter One', value: 'Carter One' },
  { label: 'Homemade Apple', value: 'Homemade Apple' },
  { label: 'Tenor Sans', value: 'Tenor Sans' },
  { label: 'Enriqueta', value: 'Enriqueta' },
  { label: 'Unna', value: 'Unna' },
  { label: 'Damion', value: 'Damion' },
  { label: 'Sarala', value: 'Sarala' },
  { label: 'Chewy', value: 'Chewy' },
  { label: 'Alex Brush', value: 'Alex Brush' },
  { label: 'PT Serif Caption', value: 'PT Serif Caption' },
  { label: 'Signika Negative', value: 'Signika Negative' },
  { label: 'Marcellus', value: 'Marcellus' },
  { label: 'Khula', value: 'Khula' },
  { label: 'Noto Serif SC', value: 'Noto Serif SC' },
  { label: 'DM Serif Display', value: 'DM Serif Display' },
  { label: 'Covered By Your Grace', value: 'Covered By Your Grace' },
  { label: 'Lilita One', value: 'Lilita One' },
  { label: 'Rambla', value: 'Rambla' },
  { label: 'Shadows Into Light Two', value: 'Shadows Into Light Two' },
  { label: 'Basic', value: 'Basic' },
  { label: 'Varela', value: 'Varela' },
  { label: 'Kreon', value: 'Kreon' },
  { label: 'Kosugi Maru', value: 'Kosugi Maru' },
  { label: 'Cantata One', value: 'Cantata One' },
  { label: 'Yrsa', value: 'Yrsa' },
  { label: 'Berkshire Swash', value: 'Berkshire Swash' },
  { label: 'Leckerli One', value: 'Leckerli One' },
  { label: 'Black Ops One', value: 'Black Ops One' },
  { label: 'Spinnaker', value: 'Spinnaker' },
  { label: 'Average', value: 'Average' },
  { label: 'Sintony', value: 'Sintony' },
  { label: 'Mukta Malar', value: 'Mukta Malar' },
  { label: 'Shrikhand', value: 'Shrikhand' },
  { label: 'Nothing You Could Do', value: 'Nothing You Could Do' },
  { label: 'Red Hat Display', value: 'Red Hat Display' },
  { label: 'Rubik Mono One', value: 'Rubik Mono One' },
  { label: 'Coda', value: 'Coda' },
  { label: 'Rancho', value: 'Rancho' },
  { label: 'Nanum Pen Script', value: 'Nanum Pen Script' },
  { label: 'Michroma', value: 'Michroma' },
  { label: 'Mada', value: 'Mada' },
  { label: 'Eczar', value: 'Eczar' },
  { label: 'Glegoo', value: 'Glegoo' },
  { label: 'Mirza', value: 'Mirza' },
  { label: 'Overpass Mono', value: 'Overpass Mono' },
  { label: 'Black Han Sans', value: 'Black Han Sans' },
  { label: 'Forum', value: 'Forum' },
  { label: 'Overlock', value: 'Overlock' },
  { label: 'Allerta', value: 'Allerta' },
  { label: 'Scheherazade', value: 'Scheherazade' },
  { label: 'Boogaloo', value: 'Boogaloo' },
  { label: 'Aleo', value: 'Aleo' },
  { label: 'Fredericka the Great', value: 'Fredericka the Great' },
  { label: 'Niconne', value: 'Niconne' },
  { label: 'Gruppo', value: 'Gruppo' },
  { label: 'Italianno', value: 'Italianno' },
  { label: 'Allan', value: 'Allan' },
  { label: 'Suez One', value: 'Suez One' },
  { label: 'Antic', value: 'Antic' },
  { label: 'Holtwood One SC', value: 'Holtwood One SC' },
  { label: 'Libre Caslon Text', value: 'Libre Caslon Text' },
  { label: 'Rufina', value: 'Rufina' },
  { label: 'Martel Sans', value: 'Martel Sans' },
  { label: 'Aldrich', value: 'Aldrich' },
  { label: 'Cabin Sketch', value: 'Cabin Sketch' },
  { label: 'Syncopate', value: 'Syncopate' },
  { label: 'Anonymous Pro', value: 'Anonymous Pro' },
  { label: 'Share Tech Mono', value: 'Share Tech Mono' },
  { label: 'Caveat Brush', value: 'Caveat Brush' },
  {
    label: 'Annie Use Your Telescope',
    value: 'Annie Use Your Telescope',
  },
  { label: 'Cinzel Decorative', value: 'Cinzel Decorative' },
  { label: 'Bentham', value: 'Bentham' },
  { label: 'Nobile', value: 'Nobile' },
  { label: 'Share', value: 'Share' },
  { label: 'Six Caps', value: 'Six Caps' },
  { label: 'Capriola', value: 'Capriola' },
  { label: 'Halant', value: 'Halant' },
  { label: 'Bowlby One SC', value: 'Bowlby One SC' },
  { label: 'Arbutus Slab', value: 'Arbutus Slab' },
  { label: 'DM Serif Text', value: 'DM Serif Text' },
  { label: 'Candal', value: 'Candal' },
  { label: 'Londrina Outline', value: 'Londrina Outline' },
  { label: 'Hanuman', value: 'Hanuman' },
  { label: 'Lateef', value: 'Lateef' },
  { label: 'Days One', value: 'Days One' },
  { label: 'Telex', value: 'Telex' },
  { label: 'Allerta Stencil', value: 'Allerta Stencil' },
  { label: 'Nixie One', value: 'Nixie One' },
  { label: 'Seaweed Script', value: 'Seaweed Script' },
  { label: 'Reenie Beanie', value: 'Reenie Beanie' },
  { label: 'Contrail One', value: 'Contrail One' },
  { label: 'Suranna', value: 'Suranna' },
  { label: 'DM Mono', value: 'DM Mono' },
  { label: 'Kameron', value: 'Kameron' },
  { label: 'Racing Sans One', value: 'Racing Sans One' },
  { label: 'Oranienbaum', value: 'Oranienbaum' },
  { label: 'Molengo', value: 'Molengo' },
  { label: 'Caudex', value: 'Caudex' },
  { label: 'Scada', value: 'Scada' },
  { label: 'Just Another Hand', value: 'Just Another Hand' },
  { label: 'Jockey One', value: 'Jockey One' },
  { label: 'Aladin', value: 'Aladin' },
  { label: 'Poller One', value: 'Poller One' },
  { label: 'Kadwa', value: 'Kadwa' },
  { label: 'Biryani', value: 'Biryani' },
  { label: 'Marcellus SC', value: 'Marcellus SC' },
  { label: 'Graduate', value: 'Graduate' },
  { label: 'Arizonia', value: 'Arizonia' },
  { label: 'Cutive Mono', value: 'Cutive Mono' },
  { label: 'Rozha One', value: 'Rozha One' },
  { label: 'Belleza', value: 'Belleza' },
  { label: 'Fira Mono', value: 'Fira Mono' },
  { label: 'IM Fell Double Pica', value: 'IM Fell Double Pica' },
  { label: 'Marmelad', value: 'Marmelad' },
  { label: 'Magra', value: 'Magra' },
  { label: 'Palanquin Dark', value: 'Palanquin Dark' },
  { label: 'Red Hat Text', value: 'Red Hat Text' },
  { label: 'Yesteryear', value: 'Yesteryear' },
  { label: 'Coustard', value: 'Coustard' },
  { label: 'Mallanna', value: 'Mallanna' },
  { label: 'Rye', value: 'Rye' },
  { label: 'Sansita', value: 'Sansita' },
  { label: 'Lustria', value: 'Lustria' },
  { label: 'Miriam Libre', value: 'Miriam Libre' },
  { label: 'Coming Soon', value: 'Coming Soon' },
  { label: 'Kristi', value: 'Kristi' },
  { label: 'Herr Von Muellerhoff', value: 'Herr Von Muellerhoff' },
  { label: 'Fauna One', value: 'Fauna One' },
  { label: 'Public Sans', value: 'Public Sans' },
  { label: 'Merienda One', value: 'Merienda One' },
  { label: 'Noto Serif KR', value: 'Noto Serif KR' },
  { label: 'Carme', value: 'Carme' },
  { label: 'Average Sans', value: 'Average Sans' },
  { label: 'Rochester', value: 'Rochester' },
  { label: 'Changa One', value: 'Changa One' },
  { label: 'Bubblegum Sans', value: 'Bubblegum Sans' },
  { label: 'Norican', value: 'Norican' },
  { label: 'Laila', value: 'Laila' },
  { label: 'Averia Serif Libre', value: 'Averia Serif Libre' },
  { label: 'Grand Hotel', value: 'Grand Hotel' },
  { label: 'Petit Formal Script', value: 'Petit Formal Script' },
  { label: 'Voltaire', value: 'Voltaire' },
  { label: 'Love Ya Like A Sister', value: 'Love Ya Like A Sister' },
  { label: 'Buenard', value: 'Buenard' },
  { label: 'Slabo 13px', value: 'Slabo 13px' },
  { label: 'Oxygen Mono', value: 'Oxygen Mono' },
  { label: 'Amethysta', value: 'Amethysta' },
  { label: 'Nanum Brush Script', value: 'Nanum Brush Script' },
  { label: 'Vast Shadow', value: 'Vast Shadow' },
  { label: 'Mr De Haviland', value: 'Mr De Haviland' },
  { label: 'Sue Ellen Francisco', value: 'Sue Ellen Francisco' },
  { label: 'Radley', value: 'Radley' },
  { label: 'Chelsea Market', value: 'Chelsea Market' },
  { label: 'Knewave', value: 'Knewave' },
  { label: 'Kelly Slab', value: 'Kelly Slab' },
  { label: 'Mukta Vaani', value: 'Mukta Vaani' },
  { label: 'Federo', value: 'Federo' },
  { label: 'Carrois Gothic', value: 'Carrois Gothic' },
  { label: 'Corben', value: 'Corben' },
  { label: 'Jost', value: 'Jost' },
  { label: 'Poly', value: 'Poly' },
  { label: 'Delius', value: 'Delius' },
  { label: 'Montaga', value: 'Montaga' },
  { label: 'ZCOOL XiaoWei', value: 'ZCOOL XiaoWei' },
  { label: 'Ovo', value: 'Ovo' },
  { label: 'Chau Philomene One', value: 'Chau Philomene One' },
  { label: 'Sen', value: 'Sen' },
  { label: 'Ceviche One', value: 'Ceviche One' },
  { label: 'Trocchi', value: 'Trocchi' },
  { label: 'GFS Didot', value: 'GFS Didot' },
  { label: 'Gilda Display', value: 'Gilda Display' },
  { label: 'Amiko', value: 'Amiko' },
  { label: 'Harmattan', value: 'Harmattan' },
  { label: 'Cambay', value: 'Cambay' },
  { label: 'Calligraffitti', value: 'Calligraffitti' },
  { label: 'Sofia', value: 'Sofia' },
  { label: 'Sniglet', value: 'Sniglet' },
  { label: 'Comic Neue', value: 'Comic Neue' },
  { label: 'Amita', value: 'Amita' },
  { label: 'Belgrano', value: 'Belgrano' },
  { label: 'Esteban', value: 'Esteban' },
  { label: 'Gugi', value: 'Gugi' },
  { label: 'Cutive', value: 'Cutive' },
  { label: 'Goudy Bookletter 1911', value: 'Goudy Bookletter 1911' },
  { label: 'Cedarville Cursive', value: 'Cedarville Cursive' },
  { label: 'Gabriela', value: 'Gabriela' },
  { label: 'Rouge Script', value: 'Rouge Script' },
  { label: 'Duru Sans', value: 'Duru Sans' },
  { label: 'Smokum', value: 'Smokum' },
  { label: 'Mansalva', value: 'Mansalva' },
  { label: 'Marvel', value: 'Marvel' },
  { label: 'IM Fell English', value: 'IM Fell English' },
  { label: 'Salsa', value: 'Salsa' },
  { label: 'Faster One', value: 'Faster One' },
  { label: 'Brawler', value: 'Brawler' },
  { label: 'Montserrat Subrayada', value: 'Montserrat Subrayada' },
  { label: 'Lekton', value: 'Lekton' },
  { label: 'Freckle Face', value: 'Freckle Face' },
  { label: 'Alike', value: 'Alike' },
  { label: 'Piedra', value: 'Piedra' },
  { label: 'Libre Barcode 39', value: 'Libre Barcode 39' },
  { label: 'Kurale', value: 'Kurale' },
  { label: 'Kosugi', value: 'Kosugi' },
  { label: 'Montez', value: 'Montez' },
  { label: 'IM Fell English SC', value: 'IM Fell English SC' },
  { label: 'Pompiere', value: 'Pompiere' },
  { label: 'UnifrakturMaguntia', value: 'UnifrakturMaguntia' },
  { label: 'Titan One', value: 'Titan One' },
  { label: 'Mrs Saint Delafield', value: 'Mrs Saint Delafield' },
  { label: 'Anaheim', value: 'Anaheim' },
  { label: 'Andada', value: 'Andada' },
  { label: 'Mandali', value: 'Mandali' },
  { label: 'Secular One', value: 'Secular One' },
  { label: 'Mate', value: 'Mate' },
  { label: 'Wendy One', value: 'Wendy One' },
  { label: 'Wallpoet', value: 'Wallpoet' },
  { label: 'Limelight', value: 'Limelight' },
  { label: 'Jua', value: 'Jua' },
  { label: 'Convergence', value: 'Convergence' },
  { label: 'Homenaje', value: 'Homenaje' },
  { label: 'Lemon', value: 'Lemon' },
  { label: 'Balthazar', value: 'Balthazar' },
  { label: 'Oleo Script Swash Caps', value: 'Oleo Script Swash Caps' },
  { label: 'Manjari', value: 'Manjari' },
  { label: 'Finger Paint', value: 'Finger Paint' },
  { label: 'Gurajada', value: 'Gurajada' },
  { label: 'Qwigley', value: 'Qwigley' },
  { label: 'Gravitas One', value: 'Gravitas One' },
  { label: 'La Belle Aurore', value: 'La Belle Aurore' },
  { label: 'Share Tech', value: 'Share Tech' },
  { label: 'Oregano', value: 'Oregano' },
  { label: 'Rakkas', value: 'Rakkas' },
  { label: 'Clicker Script', value: 'Clicker Script' },
  { label: 'Proza Libre', value: 'Proza Libre' },
  { label: 'Baumans', value: 'Baumans' },
  { label: 'Meera Inimai', value: 'Meera Inimai' },
  { label: 'Dawning of a New Day', value: 'Dawning of a New Day' },
  { label: 'Shojumaru', value: 'Shojumaru' },
  { label: 'Oxanium', value: 'Oxanium' },
  { label: 'Orienta', value: 'Orienta' },
  { label: 'Mouse Memoirs', value: 'Mouse Memoirs' },
  { label: 'Happy Monkey', value: 'Happy Monkey' },
  { label: 'Atma', value: 'Atma' },
  { label: 'Crafty Girls', value: 'Crafty Girls' },
  { label: 'Fjord One', value: 'Fjord One' },
  { label: 'Fondamento', value: 'Fondamento' },
  { label: 'Bowlby One', value: 'Bowlby One' },
  { label: 'Nova Square', value: 'Nova Square' },
  { label: 'IM Fell DW Pica', value: 'IM Fell DW Pica' },
  { label: 'Trade Winds', value: 'Trade Winds' },
  { label: 'Farro', value: 'Farro' },
  { label: 'Antic Didone', value: 'Antic Didone' },
  { label: 'Fanwood Text', value: 'Fanwood Text' },
  { label: 'Padauk', value: 'Padauk' },
  { label: 'Unkempt', value: 'Unkempt' },
  { label: 'NTR', value: 'NTR' },
  { label: 'Chela One', value: 'Chela One' },
  { label: 'Frijole', value: 'Frijole' },
  { label: 'Battambang', value: 'Battambang' },
  { label: 'Rammetto One', value: 'Rammetto One' },
  { label: 'Doppio One', value: 'Doppio One' },
  { label: 'Pavanam', value: 'Pavanam' },
  { label: 'Baskervville', value: 'Baskervville' },
  { label: 'Caladea', value: 'Caladea' },
  { label: 'Bellefair', value: 'Bellefair' },
  { label: 'Rasa', value: 'Rasa' },
  { label: 'Galada', value: 'Galada' },
  { label: 'McLaren', value: 'McLaren' },
  { label: 'Expletus Sans', value: 'Expletus Sans' },
  { label: 'Inder', value: 'Inder' },
  { label: 'Skranji', value: 'Skranji' },
  { label: 'Vesper Libre', value: 'Vesper Libre' },
  { label: 'Quando', value: 'Quando' },
  { label: 'Stardos Stencil', value: 'Stardos Stencil' },
];

export default googleFonts;
